name: MERN Stack Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-app:frontend -f Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-app:backend -f Dockerfile .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-app:frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-app:backend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up -d
